# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/controllers/views/TrafficAlerts.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2500, 1800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menuButton = QtWidgets.QPushButton(self.centralwidget)
        self.menuButton.setGeometry(QtCore.QRect(60, 40, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        self.menuButton.setFont(font)
        self.menuButton.setStyleSheet("background-color:#8c9eff ;\n"
"color: white;")
        self.menuButton.setObjectName("menuButton")
        self.districtComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.districtComboBox.setGeometry(QtCore.QRect(520, 340, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(12)
        self.districtComboBox.setFont(font)
        self.districtComboBox.setObjectName("districtComboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 330, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 0, 1881, 211))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.description_label = QtWidgets.QLabel(self.centralwidget)
        self.description_label.setGeometry(QtCore.QRect(120, 190, 2201, 151))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(14)
        self.description_label.setFont(font)
        self.description_label.setWordWrap(True)
        self.description_label.setObjectName("description_label")
        self.alertsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.alertsTable.setGeometry(QtCore.QRect(120, 420, 2321, 1161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alertsTable.sizePolicy().hasHeightForWidth())
        self.alertsTable.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(11)
        self.alertsTable.setFont(font)
        self.alertsTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.alertsTable.setShowGrid(True)
        self.alertsTable.setWordWrap(True)
        self.alertsTable.setRowCount(10)
        self.alertsTable.setObjectName("alertsTable")
        self.alertsTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.alertsTable.setItem(9, 5, item)
        self.alertsTable.horizontalHeader().setVisible(True)
        self.alertsTable.horizontalHeader().setCascadingSectionResizes(False)
        self.alertsTable.horizontalHeader().setDefaultSectionSize(340)
        self.alertsTable.horizontalHeader().setSortIndicatorShown(False)
        self.alertsTable.horizontalHeader().setStretchLastSection(True)
        self.alertsTable.verticalHeader().setVisible(False)
        self.alertsTable.verticalHeader().setDefaultSectionSize(100)
        self.alertsTable.verticalHeader().setStretchLastSection(True)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(2130, 1610, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("background-color:#e57373 ;\n"
"color: white;")
        self.exitButton.setObjectName("exitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2500, 43))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuButton.setText(_translate("MainWindow", "Back to Dashboard"))
        self.label.setText(_translate("MainWindow", "Filter by City District: "))
        self.label_2.setText(_translate("MainWindow", "Traffic Alerts"))
        self.description_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto Light\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is a log view of the information collected by drone footage and analyzed using machine learning and computer vision. You can make changes by selecting a row and choosing an action.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        item = self.alertsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Region"))
        item = self.alertsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Drone ID"))
        item = self.alertsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Route ID"))
        item = self.alertsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Description"))
        item = self.alertsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Coordinates"))
        item = self.alertsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Timestamp"))
        __sortingEnabled = self.alertsTable.isSortingEnabled()
        self.alertsTable.setSortingEnabled(False)
        item = self.alertsTable.item(0, 0)
        item.setText(_translate("MainWindow", "North Boulder"))
        item = self.alertsTable.item(0, 1)
        item.setText(_translate("MainWindow", "6f0e223a"))
        item = self.alertsTable.item(0, 2)
        item.setText(_translate("MainWindow", "9d81"))
        item = self.alertsTable.item(0, 3)
        item.setText(_translate("MainWindow", "Collision"))
        item = self.alertsTable.item(0, 4)
        item.setText(_translate("MainWindow", "-25.90891,  -97.76293"))
        item = self.alertsTable.item(0, 5)
        item.setText(_translate("MainWindow", "2018-05-24 00:00:00"))
        item = self.alertsTable.item(1, 0)
        item.setText(_translate("MainWindow", "North Boulder"))
        item = self.alertsTable.item(1, 1)
        item.setText(_translate("MainWindow", "6f0e223a"))
        item = self.alertsTable.item(1, 2)
        item.setText(_translate("MainWindow", "4d30"))
        item = self.alertsTable.item(1, 3)
        item.setText(_translate("MainWindow", "Collision"))
        item = self.alertsTable.item(1, 4)
        item.setText(_translate("MainWindow", "-43.18137, 103.86517"))
        item = self.alertsTable.item(1, 5)
        item.setText(_translate("MainWindow", "2018-06-05 00:00:00"))
        item = self.alertsTable.item(2, 0)
        item.setText(_translate("MainWindow", "North Boulder"))
        item = self.alertsTable.item(2, 1)
        item.setText(_translate("MainWindow", "6f0e223a"))
        item = self.alertsTable.item(2, 2)
        item.setText(_translate("MainWindow", "a066"))
        item = self.alertsTable.item(2, 3)
        item.setText(_translate("MainWindow", "Stable"))
        item = self.alertsTable.item(2, 4)
        item.setText(_translate("MainWindow", "23.04520, 29.98471"))
        item = self.alertsTable.item(2, 5)
        item.setText(_translate("MainWindow", "2018-05-24 00:00:00"))
        item = self.alertsTable.item(3, 0)
        item.setText(_translate("MainWindow", "Central Boulder"))
        item = self.alertsTable.item(3, 1)
        item.setText(_translate("MainWindow", "f5c17eb0"))
        item = self.alertsTable.item(3, 2)
        item.setText(_translate("MainWindow", "9d81"))
        item = self.alertsTable.item(3, 3)
        item.setText(_translate("MainWindow", "Stable"))
        item = self.alertsTable.item(3, 4)
        item.setText(_translate("MainWindow", "-58.95338, -26.72362"))
        item = self.alertsTable.item(3, 5)
        item.setText(_translate("MainWindow", "2018-11-22 00:00:00"))
        item = self.alertsTable.item(4, 0)
        item.setText(_translate("MainWindow", "University Hill"))
        item = self.alertsTable.item(4, 1)
        item.setText(_translate("MainWindow", "3367b9f1"))
        item = self.alertsTable.item(4, 2)
        item.setText(_translate("MainWindow", "4d30"))
        item = self.alertsTable.item(4, 3)
        item.setText(_translate("MainWindow", "Traffic Jam"))
        item = self.alertsTable.item(4, 4)
        item.setText(_translate("MainWindow", "-48.46068, -94.91213"))
        item = self.alertsTable.item(4, 5)
        item.setText(_translate("MainWindow", "2018-11-10 00:00:00"))
        item = self.alertsTable.item(5, 0)
        item.setText(_translate("MainWindow", "Central Boulder"))
        item = self.alertsTable.item(5, 1)
        item.setText(_translate("MainWindow", "f5c17eb0"))
        item = self.alertsTable.item(5, 2)
        item.setText(_translate("MainWindow", "a066"))
        item = self.alertsTable.item(5, 3)
        item.setText(_translate("MainWindow", "Stable"))
        item = self.alertsTable.item(5, 4)
        item.setText(_translate("MainWindow", "75.32221, 61.70063"))
        item = self.alertsTable.item(5, 5)
        item.setText(_translate("MainWindow", "2018-08-05 00:00:00"))
        item = self.alertsTable.item(6, 0)
        item.setText(_translate("MainWindow", "University Hill"))
        item = self.alertsTable.item(6, 1)
        item.setText(_translate("MainWindow", "3367b9f1"))
        item = self.alertsTable.item(6, 2)
        item.setText(_translate("MainWindow", "55b9"))
        item = self.alertsTable.item(6, 3)
        item.setText(_translate("MainWindow", "Snow Warning"))
        item = self.alertsTable.item(6, 4)
        item.setText(_translate("MainWindow", "-22.09626, 62.12066"))
        item = self.alertsTable.item(6, 5)
        item.setText(_translate("MainWindow", "2018-11-10 00:00:00"))
        item = self.alertsTable.item(7, 0)
        item.setText(_translate("MainWindow", "University Hill"))
        item = self.alertsTable.item(7, 1)
        item.setText(_translate("MainWindow", "3367b9f1"))
        item = self.alertsTable.item(7, 2)
        item.setText(_translate("MainWindow", "9d81"))
        item = self.alertsTable.item(7, 3)
        item.setText(_translate("MainWindow", "Snow Warning "))
        item = self.alertsTable.item(7, 4)
        item.setText(_translate("MainWindow", "23.24510, 76.29607"))
        item = self.alertsTable.item(7, 5)
        item.setText(_translate("MainWindow", "2018-01-29 00:00:00"))
        item = self.alertsTable.item(8, 0)
        item.setText(_translate("MainWindow", "University Hill"))
        item = self.alertsTable.item(8, 1)
        item.setText(_translate("MainWindow", "3367b9f1"))
        item = self.alertsTable.item(8, 2)
        item.setText(_translate("MainWindow", "8a82"))
        item = self.alertsTable.item(8, 3)
        item.setText(_translate("MainWindow", "Stable"))
        item = self.alertsTable.item(8, 4)
        item.setText(_translate("MainWindow", "41.91463, -117.26606"))
        item = self.alertsTable.item(8, 5)
        item.setText(_translate("MainWindow", "2018-06-05 00:00:00"))
        item = self.alertsTable.item(9, 0)
        item.setText(_translate("MainWindow", "Central Boulder"))
        item = self.alertsTable.item(9, 1)
        item.setText(_translate("MainWindow", "f5c17eb0"))
        item = self.alertsTable.item(9, 2)
        item.setText(_translate("MainWindow", "a066"))
        item = self.alertsTable.item(9, 3)
        item.setText(_translate("MainWindow", "Traffic Jam"))
        item = self.alertsTable.item(9, 4)
        item.setText(_translate("MainWindow", "-17.58704, 154.88955"))
        item = self.alertsTable.item(9, 5)
        item.setText(_translate("MainWindow", "2018-05-24 00:00:00"))
        self.alertsTable.setSortingEnabled(__sortingEnabled)
        self.exitButton.setText(_translate("MainWindow", "Exit"))

